services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fcg_ms_game_library:latest
    container_name: gameplatform_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=gameplatform;Username=gameuser;Password=gamepassword
      # Conecta ao Elasticsearch usando o IP da outra EC2
      - Elastic__Uri=http://<IP_PRIVADO_DA_EC2_ELASTICSEARCH>:9200
    ports:
      - "3001:80"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: gameplatform_postgres
    environment:
      POSTGRES_USER: gameuser
      POSTGRES_PASSWORD: gamepassword
      POSTGRES_DB: gameplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/DockerForPostgree/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gameuser -d gameplatform"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:

volumes:
  postgres_data:
